meta_product_name: "RideRiot"
meta_title: "RideRiot - Cycle with friends and see London"
meta_description: "Search fun cycle routes, see the sites and achieve rewards"
meta_image: "og-image.png" # should exist in `app/assets/images/`
twitter_account: "@LeWagonLondon"   # required for Twitter Cards